apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default-deployment
  labels:
    app: nginx-default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-default
  template:
    metadata:
      labels:
        app: nginx-default
    spec:
      containers:
        - name: nginx-default
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-default-service
spec:
  selector:
    app: nginx-default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  
  type: NodePort    
